// Generated by https://quicktype.io

export interface Documents {
  id:                 number;
  documento:          Documento;
  documentoTN:        string;
  numero:             number;
  numetoTN:           number;
  mensaje:            string;
  fechaCreacion:      string;
  fechaActualizacion: null;
}

export enum Documento {
  FS = "FS",
}
