// Generated by https://quicktype.io

export interface Document {
  response: Response;
  error:    boolean;
  message:  string;
}

export interface Response {
  facturadorCodTipoIdentificacion: string;
  facturadorNumIdentificacion:     string;
  facturadorDV:                    string;
  codSucursal:                     string;
  informacionGeneral:              InformacionGeneral;
  vendedor:                        Vendedor;
  fechaHoraEmision:                string;
  fechaHoraVencimiento:            string;
  segContrasenaSha256:             string;
  segUserName:                     string;
  type:                            string;
  syncProcessDian:                 boolean;
  isProduccion:                    boolean;
  isIntegracion:                   boolean;
  adjuntosBase64List:              any[];
}

export interface InformacionGeneral {
  prefijo:                     string;
  consecutivo:                 number;
  observacion:                 string;
  codMoneda:                   string;
  tasaTrm:                     number;
  fechaTrm:                    string;
  pagoModoList:                PagoModoList[];
  cargosListNivelDocumento:    CargosListNivelDocumento[];
  decuentosListNivelDocumento: DecuentosListNivelDocumento[];
  tributosNivelDocumentoList:  TributosNivelDocumentoList[];
  itemList:                    ItemList[];
  anticipoList:                any[];
  porcentajeReteFuente:        number;
  porcentajeReteIca:           number;
  porcentajeReteIva:           number;
  codFormaGeneracion:          string;
}

export interface CargosListNivelDocumento {
  descripcion:        string;
  porcentajeAplicado: number;
}

export interface DecuentosListNivelDocumento {
  codigo:             string;
  descripcion:        string;
  porcentajeAplicado: number;
}

export interface ItemList {
  codtipoitem:               string;
  codigo:                    string;
  descripcion:               string;
  cantidad:                  string;
  codUnidadMedida:           number;
  valorUnitario:             string;
  descuentosPorcentajesList: number[];
  cargosPorcentajesList:     number[];
  tributosList:              TributosList[];
}

export interface TributosList {
  codigo:     string;
  porcentaje: string;
}

export interface PagoModoList {
  pagoCodMetodo: string;
  pagoCodMedio:  string;
}

export interface TributosNivelDocumentoList {
  codigo:        string;
  porcentaje:    number;
  baseImponible: number;
}

export interface Vendedor {
  codTipoIdentificacion: string;
  numeroDocumento:       string;
  digitoVerificacion:    string;
  razonSocial:           string;
  codTipoContribuyente:  string;
  correo:                string;
  contactoNombre:        string;
  contactoTelefono:      string;
  contactoCorreo:        string;
  telefono:              string;
  codMunicipioCiudad:    string;
  direccion:             string;
  codRegimen:            string;
  codTributo:            string;
  codProcedencia:        string;
  listCodObligaciones:   string[];
  isCreate:              boolean;
}
