// Generated by https://quicktype.io

export interface FailDocuments {
  facn_numero:    number;
  facc_documento: FaccDocumento;
  facf_fecha:     string;
  facv_tercero:   number;
  terc_nombre:    string;
}

export enum FaccDocumento {
  FS = "FS",
}
